// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeE5LuXc17hb-BFqDTBgQPglFi6Waj5YQ',
    appId: '1:253600977718:web:bfa67341c5cc8352d2d997',
    messagingSenderId: '253600977718',
    projectId: 'my-firebase-project-5c85d',
    authDomain: 'my-firebase-project-5c85d.firebaseapp.com',
    storageBucket: 'my-firebase-project-5c85d.appspot.com',
    measurementId: 'G-XZ2832N84T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPlhFTq1m0vWLnuybYPC6DnlCjYA-yMSE',
    appId: '1:253600977718:android:d614646ad36c331fd2d997',
    messagingSenderId: '253600977718',
    projectId: 'my-firebase-project-5c85d',
    storageBucket: 'my-firebase-project-5c85d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlpAMKcCCpGy-119BXuRxHE-TnVi5UWi8',
    appId: '1:253600977718:ios:1c98b6699f18a7b2d2d997',
    messagingSenderId: '253600977718',
    projectId: 'my-firebase-project-5c85d',
    storageBucket: 'my-firebase-project-5c85d.appspot.com',
    iosClientId: '253600977718-kkbltkbsrgcjjnti1h20ohtmu4ch1q53.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfirstproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlpAMKcCCpGy-119BXuRxHE-TnVi5UWi8',
    appId: '1:253600977718:ios:1c98b6699f18a7b2d2d997',
    messagingSenderId: '253600977718',
    projectId: 'my-firebase-project-5c85d',
    storageBucket: 'my-firebase-project-5c85d.appspot.com',
    iosClientId: '253600977718-kkbltkbsrgcjjnti1h20ohtmu4ch1q53.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfirstproject',
  );
}
